version: "3.7"
services:
  php:
    build: .
    container_name: 'tourney_php'
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    working_dir: /app
    environment:
      TZ: 'Europe/Moscow'
    volumes:
      - ./app:/app
  web:
    image: nginx:stable
    container_name: 'tourney_nginx'
    working_dir: /app
    environment:
      TZ: 'Europe/Moscow'
    ports:
      - '8080:80'
    volumes:
      - ./app:/app
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
  db:
    image: mysql:latest
    container_name: 'tourney_db'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'tourney'
      MYSQL_USER: 'tourney_user'
      MYSQL_PASSWORD: 'tourney_password'
      MYSQL_ROOT_PASSWORD: 'root_password'
      TZ: 'Europe/Moscow'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-local-db:/var/lib/mysql
volumes:
  mysql-local-db: